GOOGLE_API_KEY = "AIzaSyDGm9z_6gVNS73kWO2NVAy8W3k1NBjjiDI"
GROQ_API_KEY = "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"

QDRANT_URL = "https://56f5dc6a-d2b3-40ad-ba5b-10051bb2defc.eu-central-1-0.aws.cloud.qdrant.io:6333"

QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.uL8GZ7x5RppxoP5fPtiEd16OL5vqjt4d-Y7EdE5cCn8"
